packages:
  #all packages in subdirs of packages/ and components/
  - 'providers/*'
  - 'packages/*'
 # Angular projects - these are nested under the Angular workspace root, and need version bumps during release.
  - 'apps/*'
  - 'libs/*'
